=== JadeBlue96/WeatherSystem/src/main/com/isoft/base/resources/xml_configs/wdata.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">

	<xs:element name="weather">
		<xs:complexType>
			<xs:sequence>
				<xs:element name="city" maxOccurs="unbounded"
					minOccurs="1">
					<xs:complexType>
						<xs:sequence>
							<xs:element name="country" type="xs:string"
								minOccurs="1" />
							<xs:element name="site" maxOccurs="unbounded"
								minOccurs="1">
								<xs:complexType>
									<xs:sequence>
										<xs:element name="url" type="xs:string"
											maxOccurs="unbounded" minOccurs="1" />
										<xs:element name="regex" maxOccurs="unbounded"
											minOccurs="1">
											<xs:complexType>
												<xs:all>
													<xs:element name="windst" type="xs:string"
														minOccurs="0" />
													<xs:element name="visibility" type="xs:string"
														minOccurs="0" />
													<xs:element name="temp" type="xs:string"
														minOccurs="0" />
													<xs:element name="feeltemp" type="xs:string"
														minOccurs="0" />
													<xs:element name="status" type="xs:string"
														minOccurs="0" />
													<xs:element name="wind" type="xs:string"
														minOccurs="0" />
													<xs:element name="winddir" type="xs:string"
														minOccurs="0" />
													<xs:element name="pressure" type="xs:string"
														minOccurs="0" />
													<xs:element name="humidity" type="xs:string"
														minOccurs="0" />
												</xs:all>
											</xs:complexType>
										</xs:element>
									</xs:sequence>
									<xs:attribute name="name" type="xs:string"
										use="required" />
								</xs:complexType>
							</xs:element>
						</xs:sequence>
						<xs:attribute name="name" type="xs:string"
							use="required" />
					</xs:complexType>
				</xs:element>
			</xs:sequence>
		</xs:complexType>
	</xs:element>

</xs:schema>

=== JadeBlue96/WeatherSystem/src/com/isoft/base/resources/xml_configs/wdata.xml
<?xml version="1.0" encoding="UTF-8"?>
<weather xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:noNamespaceSchemaLocation="wdata.xsd">

	<city name="Varna">
		<country>BG</country>
		<site name="Dalivali">
			<url>https://dalivali.bg?location=41</url>
			<regex>
				<temp>&lt;span class=\"number\"&gt;(.+?)&lt;\/span&gt;</temp>
				<status>&lt;h2\sclass=\"descr\"&gt;(.+?)&lt;\/h2&gt;</status>
				<feeltemp>&lt;span id="windchill-today"&gt;(.+?) &lt;span class="gr"&gt;</feeltemp>
				<wind>&lt;span\sid=\"wind-today\"&gt;(.+?)&lt;\/span&gt;</wind>
				<winddir>&lt;span\sid=\"dr-today\"&gt;(.+?)&lt;\/span&gt;</winddir>
				<pressure>&lt;span\sid=\"atmP-today\"&gt;(.+?)&lt;\/span&gt;</pressure>
				<humidity>&lt;span\sid=\"rain-today\"&gt;(.+?)&lt;\/span&gt;</humidity>
			</regex>
		</site>
		<site name="Sinoptik">
			<url>https://www.sinoptik.bg/varna-bulgaria-100726050</url>
			<regex>
				<temp>&lt;span class=\"wfCurrentTemp\">(.+?)&amp;.+C&lt;\/span&gt;</temp>
				<status>Усеща се: .+?&lt;\/span&gt;\s+&lt;strong&gt;(.+?)&lt;\/strong&gt;</status>
				<feeltemp>Усеща се: &lt;span&gt;(.+?).+&lt;\/span&gt;</feeltemp>
				<wind>wfCurrentWind\s\w+"\stitle=".+?"&gt;\s+(.+?) m\/s</wind>
				<windst>windImg.+?".+?&lt;br \/&gt;&lt;span&gt;(.+?)&lt;\/span&gt;\s+&lt;\/span&gt;</windst>
				<pressure>Атмосферно налягане:&lt;\/span&gt;\s+&lt;span class=\"wfCurrentValue\"&gt;(.+?)\shPa</pressure>
				<humidity>Влажност:&lt;\/span&gt;\s+&lt;span class=\"wfCurrentValue\"&gt;(.+?)%&lt;\/span&gt;</humidity>
				<visibility>Видимост:&lt;\/span&gt;\s+&lt;span class=\"wfCurrentValue\"&gt;(.+?) km&lt;\/span&gt;</visibility>
			</regex>
		</site>
		<site name="Dir">
			<url>https://m.dir.bg/weather/city-varna/</url>
			<regex>
				<temp>&lt;span class=\"temp\"&gt;\s+&lt;span class=\"degrees\"&gt;(.+?)°C&lt;\/span&gt;</temp>
				<wind>&lt;\/strong&gt;\s(.+?)\s\u043A\u043C/\u0447\u0430\u0441</wind>
				<status>\u0412\u0440\u0435\u043C\u0435:&lt;\/strong&gt;\s(.+?)\s&lt;br&gt;</status>
			</regex>
		</site>
	</city>

	<city name="Burgas">
		<country>BG</country>
		<site name="Dalivali">
			<url>https://dalivali.bg/?location=37</url>
			<regex>
				<temp>&lt;span class=\"number\"&gt;(.+?)&lt;\/span&gt;</temp>
				<status>&lt;h2\sclass=\"descr\"&gt;(.+?)&lt;\/h2&gt;</status>
				<feeltemp>&lt;span id="windchill-today"&gt;(.+?) &lt;span class="gr"&gt;</feeltemp>
				<wind>&lt;span\sid=\"wind-today\"&gt;(.+?)&lt;\/span&gt;</wind>
				<winddir>&lt;span\sid=\"dr-today\"&gt;(.+?)&lt;\/span&gt;</winddir>
				<pressure>&lt;span\sid=\"atmP-today\"&gt;(.+?)&lt;\/span&gt;</pressure>
				<humidity>&lt;span\sid=\"rain-today\"&gt;(.+?)&lt;\/span&gt;</humidity>
			</regex>
		</site>
		<site name="Dir">
			<url>https://m.dir.bg/weather/city-burgas/</url>
			<regex>
				<temp>&lt;span class=\"temp\"&gt;\s+&lt;span class=\"degrees\"&gt;(.+?)°C&lt;\/span&gt;</temp>
				<wind>&lt;\/strong&gt;\s(.+?)\s\u043A\u043C/\u0447\u0430\u0441</wind>
				<status>\u0412\u0440\u0435\u043C\u0435:&lt;\/strong&gt;\s(.+?)\s&lt;br&gt;</status>
			</regex>
		</site>
	</city>

	<city name="Sofia">
		<country>BG</country>
		<site name="Sinoptik">
			<url>https://www.sinoptik.bg/sofia-bulgaria-100727011</url>
			<regex>
				<temp>&lt;span class=\"wfCurrentTemp\">(.+?)&amp;.+C&lt;\/span&gt;</temp>
				<status>Усеща се: .+?&lt;\/span&gt;\s+&lt;strong&gt;(.+?)&lt;\/strong&gt;</status>
				<feeltemp>Усеща се: &lt;span&gt;(.+?).+&lt;\/span&gt;</feeltemp>
				<wind>wfCurrentWind\s\w+"\stitle=".+?"&gt;\s+(.+?) m\/s</wind>
				<windst>windImg.+?".+?&lt;br \/&gt;&lt;span&gt;(.+?)&lt;\/span&gt;\s+&lt;\/span&gt;</windst>
				<pressure>Атмосферно налягане:&lt;\/span&gt;\s+&lt;span class=\"wfCurrentValue\"&gt;(.+?)\shPa</pressure>
				<humidity>Влажност:&lt;\/span&gt;\s+&lt;span class=\"wfCurrentValue\"&gt;(.+?)%&lt;\/span&gt;</humidity>
				<visibility>Видимост:&lt;\/span&gt;\s+&lt;span class=\"wfCurrentValue\"&gt;(.+?) km&lt;\/span&gt;</visibility>
			</regex>
		</site>
		<site name="Dir">
			<url>https://m.dir.bg/weather/city-sofiya/</url>
			<regex>
				<temp>&lt;span class=\"temp\"&gt;\s+&lt;span class=\"degrees\"&gt;(.+?)°C&lt;\/span&gt;</temp>
				<wind>&lt;\/strong&gt;\s(.+?)\s\u043A\u043C/\u0447\u0430\u0441</wind>
				<status>\u0412\u0440\u0435\u043C\u0435:&lt;\/strong&gt;\s(.+?)\s&lt;br&gt;</status>
			</regex>
		</site>
	</city>

</weather>
